server:
  port: 8900
#
spring:
  datasource:
    url: jdbc:mysql://119.91.205.219:3306/mall?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: malluser
    password: malluserly
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 3000ms

jwt:
  secret: admin
  expiration: 3600
  tokenHeader: token
  tokenHead: 'Bearer '  #JWT负载中拿到开头
# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 1200000 # 验证码超期时间



#  resources:
#    # 修改默认的静态页面地址 > ResourceProperties.CLASSPATH_RESOURCE_LOCATIONS
#    static-locations: file:/data/html/zxt/web
#    #static-locations: classpath:/page/
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirm-type: correlated
#
#  data:
#    neo4j:
#      uri: bolt://114.67.78.153:7687
#      username: ongdb
#      password: 19950120
#  servlet:
#    multipart:
#      max-file-size: 30MB
#      max-request-size: 30MB
### datasourc

### shiro
shiro:
  unauthorized-url: /admin/noauth
  filter-chain:
    anon-pre: /api/**, /console/auth/resources
    anon-post: /, /index.html, /static/**, /console/admin/**, /css/**, /fonts/**, /img/**, /js/**, /console/timeLineFulltext/**

#biz:
#  es-api-domain: http://localhost:9013/api/v1
#sfc:
#  api_url: https://ocms.sfccn.com/api/webapi
#  app_secret: fcfb18a8c7a9df2dc9ce26f185b5b3ea
#leadsant:
#  graphql: http://sfc.leadsant.com/graphql